### PR TITLE
Update Gemspec to support Rails 5.1

### PR DESCRIPTION
**Pull request by garno**
This gem seems to works even with ActiveRecord 5.1. So, to add support for Rails 5.1 we only need to update the `gemspec`. This has been tested in the project I’m currently working on.

### CODE REVIEW

**Comment by garno** [comment]
@remiprev can you please 👍 this?

**Comment by remi** [comment]
@garno Can you setup Travis (the `.travis.yml` is already there) and update the `gemfiles` directory?

**Comment by pascalhamel** [comment]
@remiprev @garno I would like to merge this in order to update it to support Rails 5.2. I'll drop support for Rails 4 and ensure the specs run properly under Ruby 2.5 and 2.6. What do you think?

**Comment by remi** [comment]
Yep, sounds good to me! 👍

**Comment by garno** [comment]
👍

**Pull request merged**
